name: PHP check

on:
  push:

jobs:
  php-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
      - run: find . -type f -name '*.php' -exec php -l "{}" \; | (! grep -Ev '^No syntax errors detected in ')
      - run: exit "${?}"